// Code generated by "stringer -type TemplateID"; DO NOT EDIT.

package signTemplates

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Text-0]
	_ = x[ServerPlayerCnt-1]
}

const _TemplateID_name = "TextServerPlayerCnt"

var _TemplateID_index = [...]uint8{0, 4, 19}

func (i TemplateID) String() string {
	if i >= TemplateID(len(_TemplateID_index)-1) {
		return "TemplateID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TemplateID_name[_TemplateID_index[i]:_TemplateID_index[i+1]]
}
